trigger:
- main


variables:
    dockerRegistryServiceConnection: 'CapDefault'
    imageRepository: 'simplewebapp'
    containerRegistry: 'artemnovakregistry.azurecr.io'
    dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
    tag: '$(Build.BuildId)'
    azureSubscription: '9a6ae428-d8c3-44fe-bdf2-4e08593901a0'
    webAppName: 'simpleapp-an'

stages:
- stage: Build
  pool:
    name: Default
  jobs:
  - job: BuildAndPush
    steps:
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

- stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    pool:
      name: Default
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(webAppName)
              containers: $(containerRegistry)/$(imageRepository):$(tag)