trigger:
- main

variables:
    dockerRegistryServiceConnection: 'CapDefault'
    imageRepository: 'simplewebapp'
    containerRegistry: 'artemnovakregistry.azurecr.io'
    dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
    tag: '$(Build.BuildId)'
    azureSubscription: 'VMConnection'
    webAppName: 'simpleapp-an'
    GOVERSION: '1.23.5'
    modulePath: '$(Build.SourcesDirectory)'
    GOPATH: '$(Build.SourcesDirectory)/go'

pool:
  name: Default

stages:
- stage: Build
  jobs:
  - job: BuildTestAndDeploy
    steps:
    - task: GoTool@0
      inputs:
        version: '$(GOVERSION)'
      displayName: 'Install Go'

    - script: go version
      workingDirectory: '$(modulePath)'
      displayName: 'Initialize Go module'

    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

    - task: AzureWebAppContainer@1
      displayName: 'Deploy to Azure Web App'
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(webAppName)
        containers: $(containerRegistry)/$(imageRepository):$(tag)