trigger:
- main

pool:
  name: Default 

variables:
  GOVERSION: '1.22.5'
  GOPATH: '$(Pipeline.Workspace)/go'
  modulePath: '$(System.DefaultWorkingDirectory)'

steps:
- task: GoTool@0
  inputs:
    version: '$(GOVERSION)'
  displayName: 'Install Go'

- script: |
    go version
    go mod init mysampleapp
    go mod tidy
  workingDirectory: '$(modulePath)'
  displayName: 'Initialize Go module'

- script: go test -v ./...
  workingDirectory: '$(modulePath)'
  displayName: 'Run tests'

- script: go build -v .
  workingDirectory: '$(modulePath)'
  displayName: 'Build application'

- script: go vet ./...
  workingDirectory: '$(modulePath)'
  displayName: 'Run go vet'